[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
# WebSocket-optimized startup - use SocketIO's built-in server
startCommand = "python wsgi.py"
