[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
# Use Flask-SocketIO's built-in server (better for WebSockets than Gunicorn)
startCommand = "python wsgi.py"
